version: 2.1

jobs:
  run-tests:
    docker:
      - image: crystallang/crystal:1.6.0-alpine
    resource_class: large
    steps:
      # - run:
      #     name: "Install system dependencies"
      #     command: apk add --update --no-cache --force-overwrite git openssh-client make pcre2-dev
      - checkout
      - run:
          name: "Install dependencies"
          command: shards install
      - run:
          name: "Lint"
          command: crystal tool format --check
      - run:
          name: "Run specs"
          command: crystal spec
workflows:
  test:
    jobs:
      - run-tests
